//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OM.Client.ClientServiceSh {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/OM.EntityRepo.Entity")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode {
            get {
                return this.ClientCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCodeField, value) != true)) {
                    this.ClientCodeField = value;
                    this.RaisePropertyChanged("ClientCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceSh.IOMService")]
    public interface IOMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/CreateClient", ReplyAction="http://tempuri.org/IOMService/CreateClientResponse")]
        bool CreateClient(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/CreateClient", ReplyAction="http://tempuri.org/IOMService/CreateClientResponse")]
        System.Threading.Tasks.Task<bool> CreateClientAsync(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/DeleteClient", ReplyAction="http://tempuri.org/IOMService/DeleteClientResponse")]
        bool DeleteClient(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/DeleteClient", ReplyAction="http://tempuri.org/IOMService/DeleteClientResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientAsync(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/UpdateClient", ReplyAction="http://tempuri.org/IOMService/UpdateClientResponse")]
        bool UpdateClient(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/UpdateClient", ReplyAction="http://tempuri.org/IOMService/UpdateClientResponse")]
        System.Threading.Tasks.Task<bool> UpdateClientAsync(OM.Client.ClientServiceSh.Client item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/GetClientByID", ReplyAction="http://tempuri.org/IOMService/GetClientByIDResponse")]
        OM.Client.ClientServiceSh.Client GetClientByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOMService/GetClientByID", ReplyAction="http://tempuri.org/IOMService/GetClientByIDResponse")]
        System.Threading.Tasks.Task<OM.Client.ClientServiceSh.Client> GetClientByIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOMServiceChannel : OM.Client.ClientServiceSh.IOMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OMServiceClient : System.ServiceModel.ClientBase<OM.Client.ClientServiceSh.IOMService>, OM.Client.ClientServiceSh.IOMService {
        
        public OMServiceClient() {
        }
        
        public OMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateClient(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.CreateClient(item);
        }
        
        public System.Threading.Tasks.Task<bool> CreateClientAsync(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.CreateClientAsync(item);
        }
        
        public bool DeleteClient(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.DeleteClient(item);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientAsync(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.DeleteClientAsync(item);
        }
        
        public bool UpdateClient(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.UpdateClient(item);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClientAsync(OM.Client.ClientServiceSh.Client item) {
            return base.Channel.UpdateClientAsync(item);
        }
        
        public OM.Client.ClientServiceSh.Client GetClientByID(int id) {
            return base.Channel.GetClientByID(id);
        }
        
        public System.Threading.Tasks.Task<OM.Client.ClientServiceSh.Client> GetClientByIDAsync(int id) {
            return base.Channel.GetClientByIDAsync(id);
        }
    }
}
